

server:
  port: 8761


spring:
  application:
    name: ad-eureka-server
eureka:
  instance:
    prefer-ip-address: true
    hostname: server1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


#---
#
#spring:
#  application:
#    name: ad-eureka-server
#  profiles: server1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: server1
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://server2:8762/eureka, http://server3:8763/eureka
#
#---
#
#spring:
#  application:
#    name: ad-eureka-server
#  profiles: server2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: server2
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://server1:8761/eureka, http://server3:8763/eureka
#
#---
#
#spring:
#  application:
#    name: ad-eureka-server
#  profiles: server3
#server:
#  port: 8763
#eureka:
#  instance:
#    hostname: server3
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://server1:8761/eureka, http://server2:8762/eureka

