server:
  port: 5000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server1:8761/eureka
spring:
  application:
    name: ad-gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"


zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor



