server:
  port: 7000
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/ad?autoReconnect=True&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 124563
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server1:8761/eureka



